### ISSUE TITLE
Throughput issue with multiple queues

### ISSUE THREAD

**Issue by Lahyllas** [tsnlab/libtsn#60]
tc 명령어를 사용하기 위해 OS에 등록하는 tx/rx 큐 개수를 늘린 뒤로 간헐적으로 대역폭이 감소하는 문제가 발생하고 있습니다. 현상이 발생하면 pps가 두 자리수 이하로 현저히 감소하게 됩니다.
한 번 현상이 발생하면 머신을 껐다 켜야 해소되며, 여러 번 재시작해야 할 수도 있습니다. VM의 경우 VM만 껐다 켜도 되는 것으로 보입니다.
현상이 발생한 상태에서 드라이버를 수정해 큐를 1개로 줄이면 다시 정상 작동합니다.
큐의 개수와 대역폭 감소 폭이 관련이 있는지는 아직 확인되지 않았습니다. rx 큐를 1개로 줄이면 발생 빈도가 감소하는 것으로 추측되지만, 통계적으로 검증되진 않았습니다. (tx 큐를 줄이면 tc 명령어를 사용할 수 없습니다.)

이 현상은 RPi5 + HAT 환경에서는 발견되지 않았습니다.

큐 개수는 아래 부분에서 설정하고 있습니다.
https://github.com/tsnlab/libtsn/blob/806ee2b2ffd8be1c8322e0a4d6a0ca698d194c38/driver/XDMA/linux-kernel/xdma/xdma_mod.c#L361-L376

**Comment by tribela** [comment]
Link: SW-457
